- name: test cmd from win_command module
  hosts: chwaqmrec01.hollard.group
  tasks:
    - name: run netstat and return Ethernet stats 
      win_command: netstat -e
      register: netstat
    - debug: var=netstat
